name: Publish Docker Image Manually

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag for the image (ex: v10.0.1)'
        required: true
        type: string

jobs:
  publish_docker:
    name: Publish Docker Image
    uses: ./.github/workflows/publish_docker.yml
    with:
      tag_name: ${{ inputs.tag_name }}
    permissions:
      contents: read
      packages: write